name: data_tables
description: ListView on Mobile and Stateless Data Tables on Tablets and Desktops.
version: 1.4.0
homepage: https://github.com/rodydavis/plugins
repository: https://github.com/rodydavis/data_tables
environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.11.1

flutter:
